/// Used to call the target macro and pass a sequence of numbers as parameters to the specified macro.
///
/// The number cannot exceed `16` .
///
/// # Example
///
/// ```ignore
/// range_invoke!(my_macro,  4);
/// // eq  to ↓
/// my_macro!(0: []);
/// my_macro!(1: [P0]);
/// my_macro!(2: [P0, P1]);
/// my_macro!(3: [P0, P1, P2]);
/// my_macro!(4: [P0, P1, P2, P3]);
///
/// range_invoke!(my_macro,  4: P);
/// // eq  to ↓
/// my_macro!(0: []);
/// my_macro!(1: [0: P0]);
/// my_macro!(2: [0: P0, 1: P1]);
/// my_macro!(3: [0: P0, 1: P1, 2: P2]);
/// my_macro!(4: [0: P0, 1: P1, 2: P2, 3: P3]);
/// ```
///
/// # Generated by program
///
/// ```ignore
/// let max_num = 17;
/// let recursion = 4;
/// println!("#[macro_export]");
/// println!("macro_rules! range_invoke {{");
/// for i in 0..=max_num {
///     let k = (i / recursion) * recursion - 1;
///     println!("    ($macro:ident, {i}: P) => {{");
///     if k > 0 {
///         println!("        $crate::range_invoke!($macro, {k}: P);");
///     }
///     for it in k+1..=i {
///         print!("        $macro!({it}: [");
///         if it > 0 {
///             print!("0: P0");
///             for cnt in 1..it {
///                 print!(", {cnt}: P{cnt}");
///             }
///         }
///         println!("]);");
///     }
///     println!("    }};");
///     println!("    ($macro:ident, {i}) => {{");
///     if k > 0 {
///         println!("        $crate::range_invoke!($macro, {k});");
///     }
///     for it in k+1..=i {
///         print!("        $macro!({it}: [");
///         if it > 0 {
///             print!("P0");
///             for cnt in 1..it {
///                 print!(", P{cnt}");
///             }
///         }
///         println!("]);");
///     }
///     println!("    }};");
/// }
/// println!("}}");
/// ```
#[macro_export]
macro_rules! range_invoke {
    ($macro:ident, 0: P) => {
        $macro!(0: []);
    };
    ($macro:ident, 0) => {
        $macro!(0: []);
    };
    ($macro:ident, 1: P) => {
        $macro!(0: []);
        $macro!(1: [0: P0]);
    };
    ($macro:ident, 1) => {
        $macro!(0: []);
        $macro!(1: [P0]);
    };
    ($macro:ident, 2: P) => {
        $macro!(0: []);
        $macro!(1: [0: P0]);
        $macro!(2: [0: P0, 1: P1]);
    };
    ($macro:ident, 2) => {
        $macro!(0: []);
        $macro!(1: [P0]);
        $macro!(2: [P0, P1]);
    };
    ($macro:ident, 3: P) => {
        $macro!(0: []);
        $macro!(1: [0: P0]);
        $macro!(2: [0: P0, 1: P1]);
        $macro!(3: [0: P0, 1: P1, 2: P2]);
    };
    ($macro:ident, 3) => {
        $macro!(0: []);
        $macro!(1: [P0]);
        $macro!(2: [P0, P1]);
        $macro!(3: [P0, P1, P2]);
    };
    ($macro:ident, 4: P) => {
        $crate::range_invoke!($macro, 3: P);
        $macro!(4: [0: P0, 1: P1, 2: P2, 3: P3]);
    };
    ($macro:ident, 4) => {
        $crate::range_invoke!($macro, 3);
        $macro!(4: [P0, P1, P2, P3]);
    };
    ($macro:ident, 5: P) => {
        $crate::range_invoke!($macro, 3: P);
        $macro!(4: [0: P0, 1: P1, 2: P2, 3: P3]);
        $macro!(5: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4]);
    };
    ($macro:ident, 5) => {
        $crate::range_invoke!($macro, 3);
        $macro!(4: [P0, P1, P2, P3]);
        $macro!(5: [P0, P1, P2, P3, P4]);
    };
    ($macro:ident, 6: P) => {
        $crate::range_invoke!($macro, 3: P);
        $macro!(4: [0: P0, 1: P1, 2: P2, 3: P3]);
        $macro!(5: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4]);
        $macro!(6: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5]);
    };
    ($macro:ident, 6) => {
        $crate::range_invoke!($macro, 3);
        $macro!(4: [P0, P1, P2, P3]);
        $macro!(5: [P0, P1, P2, P3, P4]);
        $macro!(6: [P0, P1, P2, P3, P4, P5]);
    };
    ($macro:ident, 7: P) => {
        $crate::range_invoke!($macro, 3: P);
        $macro!(4: [0: P0, 1: P1, 2: P2, 3: P3]);
        $macro!(5: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4]);
        $macro!(6: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5]);
        $macro!(7: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6]);
    };
    ($macro:ident, 7) => {
        $crate::range_invoke!($macro, 3);
        $macro!(4: [P0, P1, P2, P3]);
        $macro!(5: [P0, P1, P2, P3, P4]);
        $macro!(6: [P0, P1, P2, P3, P4, P5]);
        $macro!(7: [P0, P1, P2, P3, P4, P5, P6]);
    };
    ($macro:ident, 8: P) => {
        $crate::range_invoke!($macro, 7: P);
        $macro!(8: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7]);
    };
    ($macro:ident, 8) => {
        $crate::range_invoke!($macro, 7);
        $macro!(8: [P0, P1, P2, P3, P4, P5, P6, P7]);
    };
    ($macro:ident, 9: P) => {
        $crate::range_invoke!($macro, 7: P);
        $macro!(8: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7]);
        $macro!(9: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8]);
    };
    ($macro:ident, 9) => {
        $crate::range_invoke!($macro, 7);
        $macro!(8: [P0, P1, P2, P3, P4, P5, P6, P7]);
        $macro!(9: [P0, P1, P2, P3, P4, P5, P6, P7, P8]);
    };
    ($macro:ident, 10: P) => {
        $crate::range_invoke!($macro, 7: P);
        $macro!(8: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7]);
        $macro!(9: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8]);
        $macro!(10: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9]);
    };
    ($macro:ident, 10) => {
        $crate::range_invoke!($macro, 7);
        $macro!(8: [P0, P1, P2, P3, P4, P5, P6, P7]);
        $macro!(9: [P0, P1, P2, P3, P4, P5, P6, P7, P8]);
        $macro!(10: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9]);
    };
    ($macro:ident, 11: P) => {
        $crate::range_invoke!($macro, 7: P);
        $macro!(8: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7]);
        $macro!(9: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8]);
        $macro!(10: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9]);
        $macro!(11: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10]);
    };
    ($macro:ident, 11) => {
        $crate::range_invoke!($macro, 7);
        $macro!(8: [P0, P1, P2, P3, P4, P5, P6, P7]);
        $macro!(9: [P0, P1, P2, P3, P4, P5, P6, P7, P8]);
        $macro!(10: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9]);
        $macro!(11: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10]);
    };
    ($macro:ident, 12: P) => {
        $crate::range_invoke!($macro, 11: P);
        $macro!(12: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11]);
    };
    ($macro:ident, 12) => {
        $crate::range_invoke!($macro, 11);
        $macro!(12: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11]);
    };
    ($macro:ident, 13: P) => {
        $crate::range_invoke!($macro, 11: P);
        $macro!(12: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11]);
        $macro!(13: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11, 12: P12]);
    };
    ($macro:ident, 13) => {
        $crate::range_invoke!($macro, 11);
        $macro!(12: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11]);
        $macro!(13: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12]);
    };
    ($macro:ident, 14: P) => {
        $crate::range_invoke!($macro, 11: P);
        $macro!(12: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11]);
        $macro!(13: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11, 12: P12]);
        $macro!(14: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11, 12: P12, 13: P13]);
    };
    ($macro:ident, 14) => {
        $crate::range_invoke!($macro, 11);
        $macro!(12: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11]);
        $macro!(13: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12]);
        $macro!(14: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13]);
    };
    ($macro:ident, 15: P) => {
        $crate::range_invoke!($macro, 11: P);
        $macro!(12: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11]);
        $macro!(13: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11, 12: P12]);
        $macro!(14: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11, 12: P12, 13: P13]);
        $macro!(15: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11, 12: P12, 13: P13, 14: P14]);
    };
    ($macro:ident, 15) => {
        $crate::range_invoke!($macro, 11);
        $macro!(12: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11]);
        $macro!(13: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12]);
        $macro!(14: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13]);
        $macro!(15: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14]);
    };
    ($macro:ident, 16: P) => {
        $crate::range_invoke!($macro, 15: P);
        $macro!(16: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11, 12: P12, 13: P13, 14: P14, 15: P15]);
    };
    ($macro:ident, 16) => {
        $crate::range_invoke!($macro, 15);
        $macro!(16: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15]);
    };
    ($macro:ident, 17: P) => {
        $crate::range_invoke!($macro, 15: P);
        $macro!(16: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11, 12: P12, 13: P13, 14: P14, 15: P15]);
        $macro!(17: [0: P0, 1: P1, 2: P2, 3: P3, 4: P4, 5: P5, 6: P6, 7: P7, 8: P8, 9: P9, 10: P10, 11: P11, 12: P12, 13: P13, 14: P14, 15: P15, 16: P16]);
    };
    ($macro:ident, 17) => {
        $crate::range_invoke!($macro, 15);
        $macro!(16: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15]);
        $macro!(17: [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16]);
    };
}
